# Basic site settings
title: My Jekyll Site
description: A simple Jekyll site
theme: my-jekyll-theme

# Collection settings
collections:
  pages:
    output: true

# Permalinks
permalink: /:year/:month/:day/:title.html

# Exclude files and directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
